<a href="https://colab.research.google.com/github/REDOWAN038/Security-Lab/blob/main/seurity_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task - 01(A)**

In [ ]:
def decryption(ciphertext,key):
    plaintext = ""
    for i in range(len(ciphertext)):
        ch = ciphertext[i]
        if(ch.isupper()):
            plaintext += chr((ord(ch) - (key-65)) % 26 + 65)
        elif(ch.islower()):
            plaintext += chr((ord(ch) - (key-97)) % 26 + 97)
        else:
          plaintext+=ch
    return plaintext

**Task - 01(B)**

In [ ]:
ciphertext = "XNZ XVMIDQVG VO DDXO WPDGYDIB NPNO DN BJDIB OJ WZ BMZVO VBVDI."

In [ ]:
# key = 1
print("Plain Text : ",decryption(ciphertext,1))

Plain Text :  WMY WULHCPUF UN CCWN VOCFXCHA MOMN CM AICHA NI VY ALYUN UAUCH.


In [ ]:
# key = 2
print("Plain Text : ",decryption(ciphertext,2))

Plain Text :  VLX VTKGBOTE TM BBVM UNBEWBGZ LNLM BL ZHBGZ MH UX ZKXTM TZTBG.


In [ ]:
# key = 3
print("Plain Text : ",decryption(ciphertext,3))

Plain Text :  UKW USJFANSD SL AAUL TMADVAFY KMKL AK YGAFY LG TW YJWSL SYSAF.


In [ ]:
# key = 4
print("Plain Text : ",decryption(ciphertext,4))

Plain Text :  TJV TRIEZMRC RK ZZTK SLZCUZEX JLJK ZJ XFZEX KF SV XIVRK RXRZE.


In [ ]:
# key = 5
print("Plain Text : ",decryption(ciphertext,5))

Plain Text :  SIU SQHDYLQB QJ YYSJ RKYBTYDW IKIJ YI WEYDW JE RU WHUQJ QWQYD.


In [ ]:
# key = 6
print("Plain Text : ",decryption(ciphertext,6))

Plain Text :  RHT RPGCXKPA PI XXRI QJXASXCV HJHI XH VDXCV ID QT VGTPI PVPXC.


In [ ]:
# key = 7
print("Plain Text : ",decryption(ciphertext,7))

Plain Text :  QGS QOFBWJOZ OH WWQH PIWZRWBU GIGH WG UCWBU HC PS UFSOH OUOWB.


In [ ]:
# key = 8
print("Plain Text : ",decryption(ciphertext,8))

Plain Text :  PFR PNEAVINY NG VVPG OHVYQVAT FHFG VF TBVAT GB OR TERNG NTNVA.


In [ ]:
# key = 9
print("Plain Text : ",decryption(ciphertext,9))

Plain Text :  OEQ OMDZUHMX MF UUOF NGUXPUZS EGEF UE SAUZS FA NQ SDQMF MSMUZ.


In [ ]:
# key = 10
print("Plain Text : ",decryption(ciphertext,10))

Plain Text :  NDP NLCYTGLW LE TTNE MFTWOTYR DFDE TD RZTYR EZ MP RCPLE LRLTY.


In [ ]:
# key = 11
print("Plain Text : ",decryption(ciphertext,11))

Plain Text :  MCO MKBXSFKV KD SSMD LESVNSXQ CECD SC QYSXQ DY LO QBOKD KQKSX.


In [ ]:
# key = 12
print("Plain Text : ",decryption(ciphertext,12))

Plain Text :  LBN LJAWREJU JC RRLC KDRUMRWP BDBC RB PXRWP CX KN PANJC JPJRW.


In [ ]:
# key = 13
print("Plain Text : ",decryption(ciphertext,13))

Plain Text :  KAM KIZVQDIT IB QQKB JCQTLQVO ACAB QA OWQVO BW JM OZMIB IOIQV.


In [ ]:
# key = 14
print("Plain Text : ",decryption(ciphertext,14))

Plain Text :  JZL JHYUPCHS HA PPJA IBPSKPUN ZBZA PZ NVPUN AV IL NYLHA HNHPU.


In [ ]:
# key = 15
print("Plain Text : ",decryption(ciphertext,15))

Plain Text :  IYK IGXTOBGR GZ OOIZ HAORJOTM YAYZ OY MUOTM ZU HK MXKGZ GMGOT.


In [ ]:
# key = 16
print("Plain Text : ",decryption(ciphertext,16))

Plain Text :  HXJ HFWSNAFQ FY NNHY GZNQINSL XZXY NX LTNSL YT GJ LWJFY FLFNS.


In [ ]:
# key = 17
print("Plain Text : ",decryption(ciphertext,17))

Plain Text :  GWI GEVRMZEP EX MMGX FYMPHMRK WYWX MW KSMRK XS FI KVIEX EKEMR.


In [ ]:
# key = 18
print("Plain Text : ",decryption(ciphertext,18))

Plain Text :  FVH FDUQLYDO DW LLFW EXLOGLQJ VXVW LV JRLQJ WR EH JUHDW DJDLQ.


In [ ]:
# key = 19
print("Plain Text : ",decryption(ciphertext,19))

Plain Text :  EUG ECTPKXCN CV KKEV DWKNFKPI UWUV KU IQKPI VQ DG ITGCV CICKP.


In [ ]:
# key = 20
print("Plain Text : ",decryption(ciphertext,20))

Plain Text :  DTF DBSOJWBM BU JJDU CVJMEJOH TVTU JT HPJOH UP CF HSFBU BHBJO.


In [ ]:
# key = 21
print("Plain Text : ",decryption(ciphertext,21))

Plain Text :  CSE CARNIVAL AT IICT BUILDING SUST IS GOING TO BE GREAT AGAIN.


**when we use key 21, we are getting a sentence which is not a grabage**

**Task - 02(a)**

In [12]:
# function for substitution cipher

def substitution_cipher(ciphertext, mapping):
  plaintext = ""
  for c in ciphertext:
    if c.isalpha():
      if c in mapping:
        plaintext+=mapping[c]
      else:
        plaintext+='*'
    else:
      plaintext+=c

  return plaintext

In [14]:
# printing plaintext and ciphertext

def print_result(text, words_per_line):
  cnt=0
  for c in text:
    print(c, end='')
    if(c==' '):
      cnt+=1
    if(cnt==words_per_line):
      print("\n")
      cnt=0

  print("\n\n")

In [13]:
from collections import Counter

def calc_frequency(text):
    frequency = Counter(text)
    sorted_characters = sorted(frequency.items(), key=lambda x: x[1], reverse=True)

    for char, freq in sorted_characters:
        print(f"Character: {char}, Frequency: {freq}")

In [15]:
ciphertext = "gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha aevdsxftvc tdycf \
bf gh id fgehsu aehz tmexftvcf. aevdsxf qms uvod bf gtd fgedsugt jd sddx \
jtds yvad udgf ghbut. vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut \
yhod,amzvyl, aevdsxf, msx hgtdef ftmed fghevdf ha avsxvsu qhzzhs \
uehbsx jvgt fhzdhsd.gtded med zmsl idsdavgf ha fgmlvsu bsvgdx vs \
ghbut gvzdf, mf vg tdycf gh amqd qtmyydsuvsu fvgbmgvhsf jvgt \
qhbemud. gtd vzchegmsqd ha fgmlvsu bsvgdx tmf fgebqp m qthex mzhsu \
zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu zdzhevdf ha jtmg jd tmod \
mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc bf fdd thj vsxvovxbmyf msx \
qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut gvzdf msx vsgh m ievutgde \
abgbed."

mapping = {}
words_per_line = 10
plaintext = substitution_cipher(ciphertext, mapping)
print_result(ciphertext, words_per_line)
print_result(plaintext, words_per_line)

gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha 

aevdsxftvc tdycf bf gh id fgehsu aehz tmexftvcf. aevdsxf qms 

uvod bf gtd fgedsugt jd sddx jtds yvad udgf ghbut. 

vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut yhod,amzvyl, aevdsxf, msx hgtdef 

ftmed fghevdf ha avsxvsu qhzzhs uehbsx jvgt fhzdhsd.gtded med zmsl 

idsdavgf ha fgmlvsu bsvgdx vs ghbut gvzdf, mf vg tdycf 

gh amqd qtmyydsuvsu fvgbmgvhsf jvgt qhbemud. gtd vzchegmsqd ha fgmlvsu 

bsvgdx tmf fgebqp m qthex mzhsu zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu 

zdzhevdf ha jtmg jd tmod mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc 

bf fdd thj vsxvovxbmyf msx qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut 

gvzdf msx vsgh m ievutgde abgbed.


*** ***** ** ******** ***** ******** **** *** ***** ** 

********** ***** ** ** ** ****** **** *********. ******* *** 

**** ** *** ******** ** **** **** **** **** *****. 

** ********, ****** ******* ***** ******* ****,******, *******, *** ****** 

***** ******* ** ******* ****** ****** **** *******.*

In [16]:
calc_frequency(ciphertext)

Character:  , Frequency: 105
Character: d, Frequency: 65
Character: g, Frequency: 50
Character: v, Frequency: 45
Character: f, Frequency: 43
Character: h, Frequency: 42
Character: t, Frequency: 41
Character: s, Frequency: 40
Character: e, Frequency: 32
Character: m, Frequency: 32
Character: b, Frequency: 24
Character: u, Frequency: 22
Character: x, Frequency: 19
Character: c, Frequency: 16
Character: z, Frequency: 16
Character: a, Frequency: 15
Character: y, Frequency: 13
Character: q, Frequency: 12
Character: l, Frequency: 10
Character: j, Frequency: 8
Character: ., Frequency: 6
Character: o, Frequency: 6
Character: ,, Frequency: 5
Character: i, Frequency: 3
Character: k, Frequency: 2
Character: p, Frequency: 2


In [17]:
# here we can see that character "m" is a single letter word. let's use 'a' for 'm'
mapping = {'m':'a'}
words_per_line = 10
plaintext = substitution_cipher(ciphertext, mapping)
print_result(ciphertext, words_per_line)
print_result(plaintext, words_per_line)

gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha 

aevdsxftvc tdycf bf gh id fgehsu aehz tmexftvcf. aevdsxf qms 

uvod bf gtd fgedsugt jd sddx jtds yvad udgf ghbut. 

vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut yhod,amzvyl, aevdsxf, msx hgtdef 

ftmed fghevdf ha avsxvsu qhzzhs uehbsx jvgt fhzdhsd.gtded med zmsl 

idsdavgf ha fgmlvsu bsvgdx vs ghbut gvzdf, mf vg tdycf 

gh amqd qtmyydsuvsu fvgbmgvhsf jvgt qhbemud. gtd vzchegmsqd ha fgmlvsu 

bsvgdx tmf fgebqp m qthex mzhsu zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu 

zdzhevdf ha jtmg jd tmod mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc 

bf fdd thj vsxvovxbmyf msx qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut 

gvzdf msx vsgh m ievutgde abgbed.


*** ***** ** ******** ***a* ****a*** **a* *** ***** ** 

********** ***** ** ** ** ****** **** *a*******. ******* *a* 

**** ** *** ******** ** **** **** **** **** *****. 

** a*******, ****** ******* ***** ******* ****,*a****, *******, a** ****** 

**a** ******* ** ******* ****** ****** **** *******.*

In [18]:
# in line 6, word no 8, we are seeing a two letter word. from given hints we can consider the word as "as"

mapping = {'m':'a', 'f':'s'}
words_per_line = 10
plaintext = substitution_cipher(ciphertext, mapping)
print_result(ciphertext, words_per_line)
print_result(plaintext, words_per_line)

gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha 

aevdsxftvc tdycf bf gh id fgehsu aehz tmexftvcf. aevdsxf qms 

uvod bf gtd fgedsugt jd sddx jtds yvad udgf ghbut. 

vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut yhod,amzvyl, aevdsxf, msx hgtdef 

ftmed fghevdf ha avsxvsu qhzzhs uehbsx jvgt fhzdhsd.gtded med zmsl 

idsdavgf ha fgmlvsu bsvgdx vs ghbut gvzdf, mf vg tdycf 

gh amqd qtmyydsuvsu fvgbmgvhsf jvgt qhbemud. gtd vzchegmsqd ha fgmlvsu 

bsvgdx tmf fgebqp m qthex mzhsu zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu 

zdzhevdf ha jtmg jd tmod mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc 

bf fdd thj vsxvovxbmyf msx qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut 

gvzdf msx vsgh m ievutgde abgbed.


*** ***** *s s******* *ssa* ****a**s **a* *** ***** ** 

******s*** ****s *s ** ** s***** **** *a**s***s. ******s *a* 

**** *s *** s******* ** **** **** **** ***s *****. 

** a*******, ****** *****ss ***** ******* ****,*a****, ******s, a** *****s 

s*a** s*****s ** ******* ****** ****** **** s******.*

In [19]:
# in line 1, word no 3, we are seeing a two letter word. from given hints we can consider the word as "is"

mapping = {'m':'a', 'f':'s', 'v':'i'}
words_per_line = 10
plaintext = substitution_cipher(ciphertext, mapping)
print_result(ciphertext, words_per_line)
print_result(plaintext, words_per_line)

gtd bsvgl vf fgedsugt dffml dkcymvsf gtmg gtd chjde ha 

aevdsxftvc tdycf bf gh id fgehsu aehz tmexftvcf. aevdsxf qms 

uvod bf gtd fgedsugt jd sddx jtds yvad udgf ghbut. 

vs mxxvgvhs, cdhcyd dkcedff bsvgl gtehbut yhod,amzvyl, aevdsxf, msx hgtdef 

ftmed fghevdf ha avsxvsu qhzzhs uehbsx jvgt fhzdhsd.gtded med zmsl 

idsdavgf ha fgmlvsu bsvgdx vs ghbut gvzdf, mf vg tdycf 

gh amqd qtmyydsuvsu fvgbmgvhsf jvgt qhbemud. gtd vzchegmsqd ha fgmlvsu 

bsvgdx tmf fgebqp m qthex mzhsu zmsl cdhcyd gtehbuthbg tvfghel.pddcvsu 

zdzhevdf ha jtmg jd tmod mqqhzcyvftdx gtehbuthbg tvfghel qms tdyc 

bf fdd thj vsxvovxbmyf msx qhzzbsvgvdf tmod cdefdodedx gtehbut ghbut 

gvzdf msx vsgh m ievutgde abgbed.


*** **i** is s******* *ssa* ****ai*s **a* *** ***** ** 

**i***s*i* ****s *s ** ** s***** **** *a**s*i*s. **i***s *a* 

*i** *s *** s******* ** **** **** *i** ***s *****. 

i* a**i*i**, ****** *****ss **i** ******* ****,*a*i**, **i***s, a** *****s 

s*a** s***i*s ** *i**i** ****** ****** *i** s******.*

**Task - 03**

In [ ]:
# encryption function

def encryption(plaintext, keystring):
  plaintext = plaintext.replace(" ","")     # removing space
  n = int(len(plaintext) / len(keystring))
  rem = int(len(plaintext) % len(keystring))

  for i in range(n-1):
    keystring += keystring
  for i in range(rem):
    keystring += keystring[i]

  ciphertext = ""

  for i in range(len(plaintext)):
    ciphertext += chr((ord(plaintext[i]) + ord(keystring[i])) % 26 + 65)
  return ciphertext

In [ ]:
# decryption function

def decryption(ciphertext, keystring):
  ciphertext = ciphertext.replace(" ","")     # removing space
  n = int(len(ciphertext) / len(keystring))
  rem = int(len(ciphertext) % len(keystring))

  for i in range(n-1):
    keystring += keystring
  for i in range(rem):
    keystring += keystring[i]

  plaintext = ""

  for i in range(len(ciphertext)):
    plaintext += chr((ord(ciphertext[i]) - ord(keystring[i])) % 26 + 65)
  return plaintext

In [ ]:
def print_result(a, b, key, s1, s2):
  res = ""
  j = 0
  for i in range(len(a)):
    if a[i]==' ':
      res+=' '
    else:
      res+=b[j]
      j+=1
  print(f"\n{s1} of your given {s2} by using key {key} is : {res}\n")

In [ ]:
while True:
  print("0. break\n1. encryption\n2. decryption\n")
  choice = input("enter your choice : ")
  if(choice=="0"):
    break
  elif(choice=="1"):
    plaintext = input("enter your plain text : ")
    plaintext = plaintext.upper()
    keystring = input("enter your keystring : ")
    keystring = keystring.upper()
    ciphertext = encryption(plaintext, keystring)
    print_result(plaintext, ciphertext, keystring, "cipher text", "plain text")
  else:
    ciphertext = input("enter your cipher text : ")
    ciphertext = ciphertext.upper()
    keystring = input("enter your keystring : ")
    keystring = keystring.upper()
    plaintext = decryption(ciphertext, keystring)
    print_result(ciphertext, plaintext, keystring, "plain text", "cipher text")

0. break
1. encryption
2. decryption

enter your choice : 1
enter your plain text : CSE FINAL YEAR THEORY COURSE INTRODUCTION TO COMPUER SECURITY AND FORENSICS
enter your keystring : sustcse

cipher text of your given plain text by using key SUSTCSE is : UMW YKFED SWTT LLWIJR EGYJMW BPLVGXMVVASF NG VQETMYJ LGUYJCLR CFH XIJXPKMUM

0. break
1. encryption
2. decryption

enter your choice : 2
enter your cipher text : UMW YKFED SWTT LLWIJR EGYJMW BPLVGXMVVASF NG VQETMYJ LGUYJCLR CFH XIJXPKMUM
enter your keystring : sustcse

plain text of your given cipher text by using key SUSTCSE is : CSE FINAL YEAR THEORY COURSE INTRODUCTION TO COMPUER SECURITY AND FORENSICS

0. break
1. encryption
2. decryption

enter your choice : 0


**Task - 04**

In [ ]:
# key_string = "AWESOME INTRODUCTION TO COMPUTER SECURITY AND FORENSICS"
key_string = "GYBNQKURP"

In [ ]:
# key string without spaces
key_string = key_string.replace(" ","")
key_string

'GYBNQKURP'

In [ ]:
# calculating dimension of the key_string_ascii_matrix
# we want mxm = n
import math
n = len(key_string)
m = int(math.sqrt(n))
m

3

In [ ]:
# calculating key_string_ascii_matrix
import numpy as np
key_string_ascii_matrix = np.zeros((m,m))
cnt = 0
for i in range(m):
  for j in range(m):
    key_string_ascii_matrix[i][j] = int(ord(key_string[cnt]))
    cnt+=1
key_string_ascii_matrix = key_string_ascii_matrix % 65
key_string_ascii_matrix

array([[ 6., 24.,  1.],
       [13., 16., 10.],
       [20., 17., 15.]])

In [ ]:
# encryption function
def encryption(plaintext):
  plaintext = plaintext.replace(" ","")
  n = len(plaintext)
  # calculating plaintext_ascii_matrix
  plaintext_ascii_matrix = np.zeros((n,1))
  for i in range(n):
    plaintext_ascii_matrix[i][0] = int(ord(plaintext[i]))
  plaintext_ascii_matrix = plaintext_ascii_matrix % 65

  # calculating ciphertext_ascii_matrix
  ciphertext_ascii_matrix = np.dot(key_string_ascii_matrix, plaintext_ascii_matrix)
  ciphertext_ascii_matrix = ciphertext_ascii_matrix % 26

  # generating cipher text
  ciphertext = ""
  for i in range(n):
    ciphertext += chr(int(ciphertext_ascii_matrix[i][0]) + ord('A'))
  return ciphertext

In [ ]:
# calling encryption function
plaintext = input("enter plain text : ")
ciphertext = encryption(plaintext)
ciphertext_with_spaces = ""

for char1,char2 in zip(plaintext, ciphertext):
  if char1==' ':
    ciphertext_with_spaces+=' '
  ciphertext_with_spaces+=char2

print("cipher text of given plain text : ", ciphertext_with_spaces)

enter plain text : ACT
cipher text of given plain text :  POH


In [ ]:
# decryption function
def decryption(ciphertext):
  ciphertext = ciphertext.replace(" ","")
  n = len(ciphertext)
  # calculating ciphertext_ascii_matrix
  ciphertext_ascii_matrix = np.zeros((n,1))
  for i in range(n):
    ciphertext_ascii_matrix[i][0] = int(ord(ciphertext[i]))
  ciphertext_ascii_matrix = ciphertext_ascii_matrix % 65

  # inverse of key_string_ascii_matrix
  key_string_ascii_matrix_inv = np.linalg.inv(key_string_ascii_matrix)
  key_string_ascii_matrix_inv = (key_string_ascii_matrix_inv) % 26


  # calculating plaintext_ascii_matrix
  plaintext_ascii_matrix = np.dot(key_string_ascii_matrix_inv, ciphertext_ascii_matrix)
  plaintext_ascii_matrix = plaintext_ascii_matrix % 26

  # generating plain text
  plaintext = ""
  for i in range(n):
    plaintext += chr(int(plaintext_ascii_matrix[i][0]) + ord('A'))
  return plaintext

In [ ]:
# calling decryption function
ciphertext = input("enter cipher text : ")
plaintext = decryption(ciphertext)
plaintext_with_spaces = ""

for char1,char2 in zip(ciphertext, plaintext):
  if char1==' ':
    plaintext_with_spaces+=' '
  plaintext_with_spaces+=char2

print("plain text of given plain text : ", plaintext_with_spaces)

enter cipher text : POH
[[15.]
 [14.]
 [ 7.]]
[[ 6. 24.  1.]
 [13. 16. 10.]
 [20. 17. 15.]]
plain text of given plain text :  AAA
